- name: clone repository
  become: yes
  become_user: "{{ chatbridge_user }}"
  git:
    repo: https://git.jon-e.net/jonny/chatbridge
    dest: "{{ chatbridge_user_home }}/chatbridge"
    version: "HEAD"
  register: command_result
  failed_when: "command_result.failed and 'Local modifications' not in command_result.msg"


