- name: create development .env
  become: yes
  become_user: "{{ chatbridge_user }}"
  template:
    src: chatbridge_env.j2
    dest: "{{ chatbridge_user_home}}/chatbridge/server/.env"
    mode: "600"
  when:
    - CHATBRIDGE_MODE == 'development'

- name: create production .env
  become: yes
  become_user: "{{ chatbridge_user }}"
  template:
    src: chatbridge_env.j2
    dest: "{{ chatbridge_user_home}}/chatbridge/server/dist/.env"
    mode: "600"
  when:
    - CHATBRIDGE_MODE == 'production'

- name: create https nginx config
  become: yes
  template:
    src: nginx_chatbridge.conf.j2
    dest: /etc/nginx/sites-available/chatbridge.conf
  when:
    - chatbridge_https is defined
    - chatbridge_https | bool
  notify: restart nginx

- name: create http nginx config
  become: yes
  template:
    src: nginx_chatbridge_http.conf.j2
    dest: /etc/nginx/sites-available/chatbridge.conf

  when:
    - chatbridge_https is defined
    - not chatbridge_https
  notify: restart nginx


- name: link nginx config
  become: yes
  file:
    state: link
    src: /etc/nginx/sites-available/chatbridge.conf
    dest: /etc/nginx/sites-enabled/chatbridge.conf

- name: create systemd service
  become: yes
  template:
    src: systemd_chatbridge.service.j2
    dest: /etc/systemd/system/chatbridge.service

- name: enable service
  become: yes
  service:
    name: chatbridge
    enabled: yes
    state: started

- name: restart service
  become: yes
  service:
    name: chatbridge
    state: restarted

