- name: Create chatbridge group
  group:
    name: "{{ chatbridge_user }}"
    system: true
    state: present

- name: Create chatbridge user and home directory
  become: yes
  user:
    name: "{{ chatbridge_user }}"
    state: present
    group: "{{ chatbridge_user }}"
    home: "{{ chatbridge_user_home }}"
    system: true

- name: create chatbridge log directory
  become: yes
  file:
    mode: '700'
    state: directory
    owner: "{{ chatbridge_user }}"
    path: "{{ chatbridge_log_dir }}"

- name: create chatbridge matterbridge config directory
  become: yes
  file:
    mode: '700'
    state: directory
    owner: "{{ chatbridge_user }}"
    path: "{{ chatbridge_matterbridge_configs }}"


- name: Create public directory and give permissions to www-data
  become: yes
  file:
    mode: '755'
    state: directory
    group: "www-data"
    owner: "{{ chatbridge_user }}"
    path: "{{ chatbridge_public_dir }}"

- name: Chmod home directory
  become: yes
  file:
    mode: '700'
    state: directory
    path: "{{ chatbridge_user_home }}"

