---
# defaults file for chatbridge
CHATBRIDGE_MODE: development

# development options
chatbridge_webpack_port: 8080

chatbridge_postgres_user: chatbridge
chatbridge_postgres_password: CHANGEME
chatbridge_postgres_db: chatbridge
chatbridge_postgres_port: 6500

chatbridge_user: chatbridge
chatbridge_user_home: /var/lib/chatbridge

# Where, beneath the root domain, we should host the site
# (used in nginx configs)
chatbridge_fqdn: localhost
chatbridge_webroot: ""
chatbridge_api_port: 8999

# false gives you an http-only nginx config
chatbridge_https: true
